version: "3.7"
services:
  nginx:
    container_name: ${CONTAINER_PREFIX}_nginx
    build: ./skywire-docker/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - phpfpm
    volumes:
      - ./:/var/www/html
    hostname: ${NGINX_HOSTNAME}
    depends_on:
      - phpfpm

  phpfpm:
    container_name: ${CONTAINER_PREFIX}_phpfpm
    build: ./skywire-docker/php-fpm/74
    links:
      - mysql
      - rabbitmq
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=skywire-docker

  mysql:
    container_name: ${CONTAINER_PREFIX}_mysql
    image: percona:5.7 # versions available at https://hub.docker.com/_/percona/
    ports:
      - "3306:3306"
    volumes:
      - ./skywire-docker/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker

  redis:
    container_name: ${CONTAINER_PREFIX}_redis
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: ${CONTAINER_PREFIX}_rabbitmq
    image: 'bitnami/rabbitmq:latest'
    environment:
      RABBITMQ_USERNAME: root
      RABBITMQ_PASSWORD: root
    ports:
      - "5672:5672"
      - "15672:15672"

  mailhog:
    container_name: ${CONTAINER_PREFIX}_mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"